version: '3.9'
services:

  back:
    depends_on:
      postgres:
       condition: service_healthy
    build: .
    ports:
      - "8080:8080"
    environment:
      DBNAME: proway
      DBUSER: proway
      DBPASS: proway
      DBHOST: postgres
    volumes:
      - .:/code

  postgres: 
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: proway
      POSTGRES_PASSWORD: proway
      POSTGRES_DB: proway
    volumes:
      - ./db_local:/var/lib/postgresql/data
    healthcheck:
      interval: 2s
      timeout: 2s
      retries: 5
      test: ["CMD-SHELL", "pg_isready -U proway"]
